version: "3.9"

services:
  frontend:
    build:
      context: ../Passion-Tree-Frontend
      dockerfile: Dockerfile
    image: passion-tree-frontend:dev
    container_name: passion-tree-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - FLUTTER_WEB_USE_SKIA=false
    networks:
      - passion_tree_net

networks:
  passion_tree_net:
    name: passion_tree_net

